<?php
$dalTableRBAC_AUTHENTICATION_SOURCE = array();
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_UID"] = array("type"=>200,"varname"=>"AUTH_SOURCE_UID");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_NAME"] = array("type"=>200,"varname"=>"AUTH_SOURCE_NAME");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_PROVIDER"] = array("type"=>200,"varname"=>"AUTH_SOURCE_PROVIDER");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_SERVER_NAME"] = array("type"=>200,"varname"=>"AUTH_SOURCE_SERVER_NAME");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_PORT"] = array("type"=>3,"varname"=>"AUTH_SOURCE_PORT");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_ENABLED_TLS"] = array("type"=>3,"varname"=>"AUTH_SOURCE_ENABLED_TLS");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_VERSION"] = array("type"=>200,"varname"=>"AUTH_SOURCE_VERSION");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_BASE_DN"] = array("type"=>200,"varname"=>"AUTH_SOURCE_BASE_DN");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_ANONYMOUS"] = array("type"=>3,"varname"=>"AUTH_ANONYMOUS");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_SEARCH_USER"] = array("type"=>200,"varname"=>"AUTH_SOURCE_SEARCH_USER");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_PASSWORD"] = array("type"=>200,"varname"=>"AUTH_SOURCE_PASSWORD");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_ATTRIBUTES"] = array("type"=>200,"varname"=>"AUTH_SOURCE_ATTRIBUTES");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_OBJECT_CLASSES"] = array("type"=>200,"varname"=>"AUTH_SOURCE_OBJECT_CLASSES");
$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_DATA"] = array("type"=>201,"varname"=>"AUTH_SOURCE_DATA");
	$dalTableRBAC_AUTHENTICATION_SOURCE["AUTH_SOURCE_UID"]["key"]=true;

$dal_info["Tables__RBAC_AUTHENTICATION_SOURCE"] = &$dalTableRBAC_AUTHENTICATION_SOURCE;
?>