<?php
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES = array();
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_APP_UID"] = array("type"=>3,"varname"=>"RES_APP_UID");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["APP_NUMBER"] = array("type"=>3,"varname"=>"APP_NUMBER");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["APP_STATUS"] = array("type"=>3,"varname"=>"APP_STATUS");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["ROW"] = array("type"=>200,"varname"=>"ROW");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_ITEM_1"] = array("type"=>200,"varname"=>"RES_ITEM_1");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["TIME"] = array("type"=>3,"varname"=>"TIME");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_MONTHLY_REPORT"] = array("type"=>3,"varname"=>"RES_MONTHLY_REPORT");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_ITEM_2"] = array("type"=>200,"varname"=>"RES_ITEM_2");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_ITEM_3"] = array("type"=>200,"varname"=>"RES_ITEM_3");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_ITEM_4"] = array("type"=>200,"varname"=>"RES_ITEM_4");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_ITEM_5"] = array("type"=>200,"varname"=>"RES_ITEM_5");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_RESIDENTS_CLASSIFICATION"] = array("type"=>200,"varname"=>"RES_RESIDENTS_CLASSIFICATION");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_RESIDENTS_STATE"] = array("type"=>200,"varname"=>"RES_RESIDENTS_STATE");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_THE_CURRENT_LOCAL_GOVERNMENT_MOVE_IN_DATE"] = array("type"=>200,"varname"=>"RES_THE_CURRENT_LOCAL_GOVERNMENT_MOVE_IN_DATE");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_SEX"] = array("type"=>200,"varname"=>"RES_SEX");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_BIRTHDAY"] = array("type"=>200,"varname"=>"RES_BIRTHDAY");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_JAPANESE_CLASSIFICATION"] = array("type"=>200,"varname"=>"RES_JAPANESE_CLASSIFICATION");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_MOVE_IN_THE_ORIGINAL_MUNICIPALITY_C"] = array("type"=>200,"varname"=>"RES_MOVE_IN_THE_ORIGINAL_MUNICIPALITY_C");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_HOUSING_REGISTRATION_DIVISION"] = array("type"=>200,"varname"=>"RES_HOUSING_REGISTRATION_DIVISION");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_SURNAME"] = array("type"=>200,"varname"=>"RES_SURNAME");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_NAME"] = array("type"=>200,"varname"=>"RES_NAME");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_KANA_LAST_NAME"] = array("type"=>200,"varname"=>"RES_KANA_LAST_NAME");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_KANA_NAME"] = array("type"=>200,"varname"=>"RES_KANA_NAME");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_PERMANENT_RESIDENCE"] = array("type"=>200,"varname"=>"RES_PERMANENT_RESIDENCE");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_LEGAL_DOMICILE_ADDRESS_CODE"] = array("type"=>200,"varname"=>"RES_LEGAL_DOMICILE_ADDRESS_CODE");
$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_COUNTRY_OF_CITIZENSHIP"] = array("type"=>200,"varname"=>"RES_COUNTRY_OF_CITIZENSHIP");
	$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES["RES_APP_UID"]["key"]=true;

$dal_info["Tables__PMT_RESIDENTS_BASIC_ATTRIBUTES"] = &$dalTablePMT_RESIDENTS_BASIC_ATTRIBUTES;
?>