<?php
$dalTableCALENDAR_BUSINESS_HOURS = array();
$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_UID"] = array("type"=>200,"varname"=>"CALENDAR_UID");
$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_DAY"] = array("type"=>200,"varname"=>"CALENDAR_BUSINESS_DAY");
$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_START"] = array("type"=>200,"varname"=>"CALENDAR_BUSINESS_START");
$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_END"] = array("type"=>200,"varname"=>"CALENDAR_BUSINESS_END");
	$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_UID"]["key"]=true;
	$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_DAY"]["key"]=true;
	$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_START"]["key"]=true;
	$dalTableCALENDAR_BUSINESS_HOURS["CALENDAR_BUSINESS_END"]["key"]=true;

$dal_info["Tables__CALENDAR_BUSINESS_HOURS"] = &$dalTableCALENDAR_BUSINESS_HOURS;
?>