<?php
$dalTablemodx_site_content = array();
$dalTablemodx_site_content["id"] = array("type"=>3,"varname"=>"id");
$dalTablemodx_site_content["type"] = array("type"=>200,"varname"=>"type");
$dalTablemodx_site_content["contentType"] = array("type"=>200,"varname"=>"contentType");
$dalTablemodx_site_content["pagetitle"] = array("type"=>200,"varname"=>"pagetitle");
$dalTablemodx_site_content["longtitle"] = array("type"=>200,"varname"=>"longtitle");
$dalTablemodx_site_content["description"] = array("type"=>200,"varname"=>"description");
$dalTablemodx_site_content["alias"] = array("type"=>200,"varname"=>"alias");
$dalTablemodx_site_content["link_attributes"] = array("type"=>200,"varname"=>"link_attributes");
$dalTablemodx_site_content["published"] = array("type"=>3,"varname"=>"published");
$dalTablemodx_site_content["pub_date"] = array("type"=>3,"varname"=>"pub_date");
$dalTablemodx_site_content["unpub_date"] = array("type"=>3,"varname"=>"unpub_date");
$dalTablemodx_site_content["parent"] = array("type"=>3,"varname"=>"parent");
$dalTablemodx_site_content["isfolder"] = array("type"=>3,"varname"=>"isfolder");
$dalTablemodx_site_content["introtext"] = array("type"=>201,"varname"=>"introtext");
$dalTablemodx_site_content["content"] = array("type"=>201,"varname"=>"content");
$dalTablemodx_site_content["richtext"] = array("type"=>16,"varname"=>"richtext");
$dalTablemodx_site_content["template"] = array("type"=>3,"varname"=>"template");
$dalTablemodx_site_content["menuindex"] = array("type"=>3,"varname"=>"menuindex");
$dalTablemodx_site_content["searchable"] = array("type"=>3,"varname"=>"searchable");
$dalTablemodx_site_content["cacheable"] = array("type"=>3,"varname"=>"cacheable");
$dalTablemodx_site_content["createdby"] = array("type"=>3,"varname"=>"createdby");
$dalTablemodx_site_content["createdon"] = array("type"=>3,"varname"=>"createdon");
$dalTablemodx_site_content["editedby"] = array("type"=>3,"varname"=>"editedby");
$dalTablemodx_site_content["editedon"] = array("type"=>3,"varname"=>"editedon");
$dalTablemodx_site_content["deleted"] = array("type"=>3,"varname"=>"deleted");
$dalTablemodx_site_content["deletedon"] = array("type"=>3,"varname"=>"deletedon");
$dalTablemodx_site_content["deletedby"] = array("type"=>3,"varname"=>"deletedby");
$dalTablemodx_site_content["publishedon"] = array("type"=>3,"varname"=>"publishedon");
$dalTablemodx_site_content["publishedby"] = array("type"=>3,"varname"=>"publishedby");
$dalTablemodx_site_content["menutitle"] = array("type"=>200,"varname"=>"menutitle");
$dalTablemodx_site_content["donthit"] = array("type"=>16,"varname"=>"donthit");
$dalTablemodx_site_content["haskeywords"] = array("type"=>16,"varname"=>"haskeywords");
$dalTablemodx_site_content["hasmetatags"] = array("type"=>16,"varname"=>"hasmetatags");
$dalTablemodx_site_content["privateweb"] = array("type"=>16,"varname"=>"privateweb");
$dalTablemodx_site_content["privatemgr"] = array("type"=>16,"varname"=>"privatemgr");
$dalTablemodx_site_content["content_dispo"] = array("type"=>16,"varname"=>"content_dispo");
$dalTablemodx_site_content["hidemenu"] = array("type"=>16,"varname"=>"hidemenu");
$dalTablemodx_site_content["alias_visible"] = array("type"=>3,"varname"=>"alias_visible");
$dalTablemodx_site_content["modex_site_htmlsnippet_id"] = array("type"=>3,"varname"=>"modex_site_htmlsnippet_id");
$dalTablemodx_site_content["modx_site_snippet_id"] = array("type"=>3,"varname"=>"modx_site_snippet_id");
	$dalTablemodx_site_content["id"]["key"]=true;

$dal_info["Tables__modx_site_content"] = &$dalTablemodx_site_content;
?>